sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - graphviz

script:
  - doxygen Doxyfile
  - cd html
  - touch .nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
